[build]
dockerfilePath = "Dockerfile"

[build.args]
CACHEBUST = "2026-01-22-v2"
VITE_SUPABASE_URL = "${{VITE_SUPABASE_URL}}"
VITE_SUPABASE_ANON_KEY = "${{VITE_SUPABASE_ANON_KEY}}"
VITE_OAUTH_PORTAL_URL = "${{VITE_OAUTH_PORTAL_URL}}"
